<?php

$messages['api_error_contact_admin'] = 'Es ist ein Fehler bei der E-Mail-Generierung aufgetreten, bitte kontaktieren Sie den Administrator.';

$messages['ai_no_instructions'] = 'Geben Sie Anweisungen ein';
$messages['ai_instructions_too_long'] = 'Ihre Anweisungen sind zu lang; sie dürfen maximal $n Zeichen enthalten.';
$messages['ai_empty_response'] = 'Der Server hat eine leere Antwort zurückgegeben';

$messages['ai_validation_error_not_enough_characters_instruction'] = 'Die Anzahl der Zeichen muss größer als 1 sein!';
$messages['ai_validation_error_invalid_input_instructions'] = "Das Feld 'Anweisungen' muss gültigen Text enthalten!";
$messages['ai_validation_error_invalid_input_subject'] = "Das Feld 'Betreff' muss gültigen Text enthalten.";
$messages['ai_validation_error_invalid_recipient_email_address'] = 'Die E-Mail-Adresse des Empfängers ist ungültig.';
$messages['ai_validation_error_invalid_sender_email_address'] = 'Die E-Mail-Adresse des Absenders ist ungültig.';
$messages['ai_validation_error_invalid_style'] = "Das Feld 'Stil' ist ungültig!";
$messages['ai_validation_error_invalid_language'] = "Das Feld 'Sprache' ist ungültig!";
$messages['ai_validation_error_invalid_length'] = "Das Feld 'Länge' ist ungültig!";
$messages['ai_validation_error_invalid_creativity'] = "Das Feld 'Kreativität' ist ungültig!";
$messages['ai_validation_error_sender_name_mandatory'] = 'Der Name des Absenders ist erforderlich!';
$messages['ai_validation_error_invalid_sender_name_text'] = "Das Feld 'Absendername' muss gültigen Text enthalten!";
$messages['ai_validation_error_invalid_recipient_name_text'] = "Das Feld 'Empfängername' muss gültigen Text enthalten!";
$messages['ai_validation_error_not_enough_characters_sender_name'] = "Das Feld 'Absendername' muss mindestens 3 Zeichen lang sein.";
$messages['ai_validation_error_not_enough_characters_recipient_name'] = "Das Feld 'Empfängername' muss mindestens 3 Zeichen lang sein, wenn es angegeben ist.";

$messages['ai_predefined_request_error'] = 'Bei der Verarbeitung der Anfrage ist ein Fehler aufgetreten.';
$messages['ai_predefined_delete_error'] = 'Beim Löschen der Anleitung ist ein Fehler aufgetreten.';
$messages['ai_predefined_get_all_instructions_error'] = 'Beim Abrufen der Anleitungen ist ein Fehler aufgetreten.';
$messages['ai_predefined_get_specific_instruction_error'] = 'Beim Abrufen der Informationen zur Anleitung ist ein Fehler aufgetreten.';
$messages['ai_predefined_content_error'] = 'Fehler beim Anzeigen der Seite.';
$messages['ai_predefined_max_instructions_error'] = 'Die maximale Anzahl verfügbarer Anweisungen beträgt 10!';
$messages['ai_predefined_max_instructions_error'] = 'The maximum number of available instructions is 10!';
$messages['ai_predefined_max_instructions_error'] = 'Maksimalan broj dostupnih uputa je 10!';
$messages['ai_predefined_max_instructions_error'] = 'Het maximale aantal beschikbare instructies is 20!';
