<?php

$messages['api_error_contact_admin'] = 'Virhe sähköpostin luomisessa, ota yhteyttä ylläpitäjään.';

$messages['ai_no_instructions'] = 'Kirjoita ohjeet';
$messages['ai_instructions_too_long'] = 'Ohjeesi on liian pitkä; se voi olla enintään $n merkkiä.';
$messages['ai_empty_response'] = 'Palvelin palautti tyhjän vastauksen';

$messages['ai_validation_error_not_enough_characters_instruction'] = 'Merkkien määrän on oltava suurempi kuin 1!';
$messages['ai_validation_error_invalid_input_instructions'] = "Kentän 'Ohjeet' on sisällettävä kelvollista tekstiä!";
$messages['ai_validation_error_invalid_input_subject'] = "Kentän 'Aihe' on sisällettävä kelvollista tekstiä.";
$messages['ai_validation_error_invalid_recipient_email_address'] = "Vastaanottajan sähköpostiosoite on virheellinen.";
$messages['ai_validation_error_invalid_sender_email_address'] = "Lähettäjän sähköpostiosoite on virheellinen.";
$messages['ai_validation_error_invalid_style'] = "Kenttä 'Tyyli' on virheellinen!";
$messages['ai_validation_error_invalid_language'] = "Kenttä 'Kieli' on virheellinen!";
$messages['ai_validation_error_invalid_length'] = "Kenttä 'Pituus' on virheellinen!";
$messages['ai_validation_error_invalid_creativity'] = "Kenttä 'Luovuus' on virheellinen!";
$messages['ai_validation_error_sender_name_mandatory'] = "Lähettäjän nimi on pakollinen!";
$messages['ai_validation_error_invalid_sender_name_text'] = "Kentän 'Lähettäjän nimi' on sisällettävä kelvollista tekstiä!";
$messages['ai_validation_error_invalid_recipient_name_text'] = "Kentän 'Vastaanottajan nimi' on sisällettävä kelvollista tekstiä!";
$messages['ai_validation_error_not_enough_characters_sender_name'] = "Kentän 'Lähettäjän nimi' on oltava vähintään 3 merkkiä pitkä.";
$messages['ai_validation_error_not_enough_characters_recipient_name'] = "Kentän 'Vastaanottajan nimi' on oltava vähintään 3 merkkiä pitkä, jos se annetaan.";

$messages['ai_predefined_request_error'] = 'Virhe pyynnön käsittelyssä.';
$messages['ai_predefined_delete_error'] = 'Virhe ohjeen poistamisessa.';
$messages['ai_predefined_get_all_instructions_error'] = 'Virhe ohjeiden haussa.';
$messages['ai_predefined_get_specific_instruction_error'] = 'Virhe haettaessa tietoja ohjeesta.';
$messages['ai_predefined_content_error'] = 'Virhe sivun näyttämisessä.';
$messages['ai_predefined_max_instructions_error'] = 'Ohjeiden enimmäismäärä on 20!';
