<?php

$messages['api_error_contact_admin'] = 'Došlo je do greške prilikom generiranja e-pošte, molimo kontaktirajte administratora.';

$messages['ai_no_instructions'] = 'Upišite upute';
$messages['ai_instructions_too_long'] = 'Vaše upute su preduge; mogu imati najviše $n znakova.';
$messages['ai_empty_response'] = 'Server je vratio prazan odgovor';

$messages['ai_validation_error_not_enough_characters_instruction'] = 'Broj znakova mora biti veći od 1!';
$messages['ai_validation_error_invalid_input_instructions'] = "Polje 'upute' mora sadržavati valjan tekst!";
$messages['ai_validation_error_invalid_input_subject'] = "Polje 'predmet' mora sadržavati valjan tekst.";
$messages['ai_validation_error_invalid_recipient_email_address'] = 'E-mail adresa primatelja je nevažeća.';
$messages['ai_validation_error_invalid_sender_email_address'] = 'E-mail adresa pošiljatelja je nevažeća.';
$messages['ai_validation_error_invalid_style'] = "Polje 'stil' je nevažeće!";
$messages['ai_validation_error_invalid_language'] = "Polje 'jezik' je nevažeće!";
$messages['ai_validation_error_invalid_length'] = "Polje 'dužina' je nevažeće!";
$messages['ai_validation_error_invalid_creativity'] = "Polje 'kreativnost' je nevažeće!";
$messages['ai_validation_error_sender_name_mandatory'] = 'Ime pošiljatelja je obavezno!';
$messages['ai_validation_error_invalid_sender_name_text'] = "Polje 'Ime pošiljatelja' mora sadržavati valjan tekst!";
$messages['ai_validation_error_invalid_recipient_name_text'] = "Polje 'Ime primatelja' mora sadržavati valjan tekst!";
$messages['ai_validation_error_not_enough_characters_sender_name'] = "Polje 'Ime pošiljatelja' mora imati najmanje 3 znaka.";
$messages['ai_validation_error_not_enough_characters_recipient_name'] = "Polje 'Ime primatelja' mora imati najmanje 3 znaka ako je navedeno.";

$messages['ai_predefined_request_error'] = 'Došlo je do greške prilikom obrade zahtjeva.';
$messages['ai_predefined_delete_error'] = 'Došlo je do greške prilikom brisanja instrukcije.';
$messages['ai_predefined_get_all_instructions_error'] = 'Došlo je do greške prilikom dohvaćanja instrukcija.';
$messages['ai_predefined_get_specific_instruction_error'] = 'Došlo je do greške prilikom dohvaćanja informacija za instrukciju.';
$messages['ai_predefined_content_error'] = 'Greška prilikom prikaza stranice.';
$messages['ai_predefined_max_instructions_error'] = 'Maksimalan broj dostupnih uputa je 10!';
