<?php

$messages['api_error_contact_admin'] = 'Er is een fout opgetreden bij het genereren van de e-mail, neem contact op met de beheerder.';

$messages['ai_no_instructions'] = 'Voer instructies in';
$messages['ai_instructions_too_long'] = 'Uw instructies zijn te lang; ze mogen maximaal $n tekens bevatten.';
$messages['ai_empty_response'] = 'Server heeft een leeg antwoord geretourneerd';

$messages['ai_validation_error_not_enough_characters_instruction'] = 'Aantal tekens moet groter zijn dan 1!';
$messages['ai_validation_error_invalid_input_instructions'] = "Het veld 'instructies' moet geldige tekst bevatten!";
$messages['ai_validation_error_invalid_input_subject'] = "Het veld 'onderwerp' moet geldige tekst bevatten.";
$messages['ai_validation_error_invalid_recipient_email_address'] = 'E-mailadres van de ontvanger is ongeldig.';
$messages['ai_validation_error_invalid_sender_email_address'] = 'E-mailadres van de afzender is ongeldig.';
$messages['ai_validation_error_invalid_style'] = "Het veld 'stijl' is ongeldig!";
$messages['ai_validation_error_invalid_language'] = "Het veld 'taal' is ongeldig!";
$messages['ai_validation_error_invalid_length'] = "Het veld 'lengte' is ongeldig!";
$messages['ai_validation_error_invalid_creativity'] = "Het veld 'creativiteit' is ongeldig!";
$messages['ai_validation_error_sender_name_mandatory'] = 'Naam van de afzender is verplicht!';
$messages['ai_validation_error_invalid_sender_name_text'] = "Het veld 'Naam afzender' moet geldige tekst bevatten!";
$messages['ai_validation_error_invalid_recipient_name_text'] = "Het veld 'Naam ontvanger' moet geldige tekst bevatten!";
$messages['ai_validation_error_not_enough_characters_sender_name'] = "Het veld 'Naam afzender' moet minimaal 3 tekens bevatten.";
$messages['ai_validation_error_not_enough_characters_recipient_name'] = "Het veld 'Naam ontvanger' moet minimaal 3 tekens bevatten als het is ingevuld.";

$messages['ai_predefined_request_error'] = 'Er is een fout opgetreden bij het verwerken van het verzoek.';
$messages['ai_predefined_delete_error'] = 'Er is een fout opgetreden bij het verwijderen van de instructie.';
$messages['ai_predefined_get_all_instructions_error'] = 'Er is een fout opgetreden bij het ophalen van instructies.';
$messages['ai_predefined_get_specific_instruction_error'] = 'Er is een fout opgetreden bij het ophalen van informatie voor de instructie.';
$messages['ai_predefined_content_error'] = 'Fout bij het weergeven van de pagina.';
$messages['ai_predefined_max_instructions_error'] = "Het maximale aantal beschikbare instructies is 10!";