<?php

$messages['api_error_contact_admin'] = 'Ett fel uppstod när e-postmeddelandet skulle genereras, vänligen kontakta administratören.';

$messages['ai_no_instructions'] = 'Skriv instruktioner';
$messages['ai_instructions_too_long'] = 'Dina instruktioner är för långa; de kan maximalt innehålla $n tecken.';
$messages['ai_empty_response'] = 'Servern returnerade ett tomt svar';

$messages['ai_validation_error_not_enough_characters_instruction'] = 'Antalet tecken måste vara fler än 1!';
$messages['ai_validation_error_invalid_input_instructions'] = "Fältet 'Instruktioner' måste innehålla giltig text!";
$messages['ai_validation_error_invalid_input_subject'] = "Fältet 'Ämne' måste innehålla giltig text.";
$messages['ai_validation_error_invalid_recipient_email_address'] = "Mottagarens e-postadress är ogiltig.";
$messages['ai_validation_error_invalid_sender_email_address'] = "Avsändarens e-postadress är ogiltig.";
$messages['ai_validation_error_invalid_style'] = "Fältet 'Stil' är ogiltigt!";
$messages['ai_validation_error_invalid_language'] = "Fältet 'Språk' är ogiltigt!";
$messages['ai_validation_error_invalid_length'] = "Fältet 'Längd' är ogiltigt!";
$messages['ai_validation_error_invalid_creativity'] = "Fältet 'Kreativitet' är ogiltigt!";
$messages['ai_validation_error_sender_name_mandatory'] = "Avsändarens namn krävs!";
$messages['ai_validation_error_invalid_sender_name_text'] = "Fältet 'Avsändarens namn' måste innehålla giltig text!";
$messages['ai_validation_error_invalid_recipient_name_text'] = "Fältet 'Mottagarens namn' måste innehålla giltig text!";
$messages['ai_validation_error_not_enough_characters_sender_name'] = "Fältet 'Avsändarens namn' måste vara minst 3 tecken långt.";
$messages['ai_validation_error_not_enough_characters_recipient_name'] = "Fältet 'Mottagarens namn' måste vara minst 3 tecken långt om det anges.";

$messages['ai_predefined_request_error'] = 'Ett fel uppstod när begäran behandlades.';
$messages['ai_predefined_delete_error'] = 'Ett fel uppstod när instruktionen skulle tas bort.';
$messages['ai_predefined_get_all_instructions_error'] = 'Ett fel uppstod när instruktionerna skulle hämtas.';
$messages['ai_predefined_get_specific_instruction_error'] = 'Ett fel uppstod när information om instruktionen skulle hämtas.';
$messages['ai_predefined_content_error'] = 'Fel vid visning av sidan.';
$messages['ai_predefined_max_instructions_error'] = 'Det maximala antalet tillgängliga instruktioner är 20!';
