<?php

$labels = [];

$labels['ai_dialog_button_text'] = 'AI';
$labels['ai_dialog_button_title'] = 'Sastavite poruku pomoću AI';
$labels['ai_dialog_title'] = 'Sastavite poruku pomoću AI';

$labels['ai_label_to'] = 'Ime primatelja';
$labels['ai_label_from'] = 'Ime pošiljaoca';
$labels['ai_label_style'] = 'Stil';
$labels['ai_label_length'] = 'Dužina';
$labels['ai_label_language'] = 'Jezik';
$labels['ai_label_creativity'] = 'Kreativnost';
$labels['ai_label_instructions'] = 'Instrukcije';
$labels['ai_no_change'] = 'Bez promjene';
$labels['ai_instructions_placeholder'] = 'Primjer: zatražite promjenu termina za sljedeću sedmicu';

$labels['ai_style_assertive'] = 'Samopouzdano';
$labels['ai_style_casual'] = 'Neformalno';
$labels['ai_style_enthusiastic'] = 'Entuzijastično';
$labels['ai_style_funny'] = 'Smiješno';
$labels['ai_style_informational'] = 'Informativno';
$labels['ai_style_professional'] = 'Profesionalno';
$labels['ai_style_urgent'] = 'Hitno';
$labels['ai_style_witty'] = 'Domišljato';
$labels['ai_style_persuasive'] = 'Uvjerljivo';

$labels['ai_length_short'] = 'Kratko';
$labels['ai_length_medium'] = 'Srednje';
$labels['ai_length_long'] = 'Dugo';

$labels['ai_creativity_low'] = 'Nisko';
$labels['ai_creativity_medium'] = 'Srednje';
$labels['ai_creativity_high'] = 'Visoko';

$labels['ai_language_bosnian'] = 'Bosnian (Bosanski)';
$labels['ai_language_croatian'] = 'Croatian (Hrvatski)';
$labels['ai_language_english'] = 'English (US)';
$labels['ai_language_german'] = 'German (Deutsch)';
$labels['ai_language_dutch'] = 'Dutch (Nederlands)';

$labels['ai_error_sender_name'] = 'Unesite ime pošiljatelja!';
$labels['ai_error_recipient_name'] = 'Ime primatelja prazno (Opcionalno)';
$labels['ai_error_instructions'] = 'Unesite instrukciju!';

$labels['ai_request_error'] = 'Usluga nije dostupna. Molimo pokušajte ponovo kasnije.';

$labels['ai_insert_email'] = 'Umetni e-mail';
$labels['ai_generate_email'] = 'Generiši e-mail';
$labels['ai_generate_again'] = 'Generiši ponovo';
$labels['ai_stop_generating'] = 'Zaustavi Generisanje';
$labels['ai_error_help_button'] = 'Pomoć';

$labels['ai_button_show_instructions'] = 'Primjeri Instrukcija';
$labels['ai_help_button_back'] = 'Nazad';
$labels['ai_button_fix_selected_text'] = ' Ispravi Odabrani Tekst';
$labels['ai_help_title'] = 'Pomoć & Primjeri';
$labels['ai_help_use_example'] = '(Koristi ovo)';

$labels['ai_fix_selected_text_title'] = 'Ispravi Odabrani Tekst';
$labels['ai_selected_text'] = 'Odabrani Tekst';
$labels['ai_fix_instructions'] = 'Instrukcija za Ispravljanje';

$labels['settings_menu_text'] = 'Umjetna Inteligencija';
$labels['setting_default_options'] = 'Sastavljanje poruka sa AI';
$labels['setting_ai_style'] = 'Stil';
$labels['setting_ai_length'] = 'Dužina';
$labels['setting_ai_language'] = 'Jezik';
$labels['setting_ai_creativity'] = 'Kreativnost';

$labels['ai_tip_to'] = 'Ime primaoca nove e-pošte. Možete navesti više od jednog imena ili koristiti nizove poput "svi", "tim" itd.';
$labels['ai_tip_from'] = 'Novi email će biti potpisan ovim imenom.';
$labels['ai_tip_style'] = 'Željeni stil pisanja za novu e-poštu.';
$labels['ai_tip_length'] = 'Željena dužina nove e-pošte.';
$labels['ai_tip_language'] = 'Jezik na kojem bi trebao biti napisan novi email. Navedite "Bez promjene" da pišete na jeziku na kojem su date upute.';
$labels['ai_tip_creativity'] = 'Veća kreativnost će generirati nepredvidljivije i raznolikije e-poruke; niža kreativnost će generisati e-poruke koje su više činjenične i tačnije.';
$labels['ai_tip_instructions'] = 'Upute o tome šta uključiti u novu e-poštu. Kliknite na dugme Primjeri Instrukcija da vidite neke primjere.';

$labels['ai_help_info'] = 'Recite AI o e-poruci koju želite da napišete. Uključite pojedinosti, kao što su imena, datumi, lokacije, razlozi, itd. Također možete tražiti kreativne ideje ili objašnjenja. Nakon što se e-mail generira, moći ćete ga podesiti i umetnuti u AI stranicu. Evo nekoliko primjera uputa za početak';

$labels['ai_help_example_1'] = 'pozdravi se';
$labels['ai_help_example_2'] = 'današnji sastanak je otkazan';
$labels['ai_help_example_3'] = 'Dogovorio sam sastanak sa Margy u srijedu u 15:00, pripremio sam prezentaciju o prednostima korištenja vještačke inteligencije u našim marketinškim kampanjama da je ubijedim';
$labels['ai_help_example_4'] = 'odlučili smo da dodamo podršku za sadržaj generisan vještačkom inteligencijom, objasni ukratko šta je to';
$labels['ai_help_example_5'] = 'nastavak radnog zadatka od prosle sedmice, treba mi sutra';
$labels['ai_help_example_6'] = 'traži povišicu, nisam je dobio više od godinu dana';
$labels['ai_help_example_7'] = 'podsjetite da se sutra preda izvještaj ili će tim imati problema sa Margy koja je pod stresom';
$labels['ai_help_example_8'] = 'pišite kupcima o 20% popusta na sve proizvode do utorka, prodajemo odjeću';
$labels['ai_help_example_9'] = 'zamolite da napišete Lauri i recite joj da organizira druženje za Kevinov rođendan ovog vikenda';
$labels['ai_help_example_10'] = 'pitajte o napretku s novom web-stranicom, uključite 5 ideja za marketinške slogane za naslovnu stranicu, radimo popravke automobila';
$labels['ai_help_example_11'] = 'informativni list o novim vpn funkcijama koje smo dodali: wireguard protokol, prosljeđivanje portova, kill switch, namjenski IP; objasni šta su';
$labels['ai_help_example_12'] = 'informativni list o novom programu lojalnosti, početni trošak je 10$ za karticu, a zatim do 20% popusta na većinu proizvoda za godinu dana';
$labels['ai_help_example_13'] = 'umrežavanje e-poštom nekome kome se divim i s kim se želim profesionalno povezati';
$labels['ai_help_example_14'] = 'profesionalno izražavanje zahvalnosti na jučerašnjoj pomoći oko projekta';
$labels['ai_help_example_15'] = 'smisli 10 ideja o strategijama za kreiranje efikasne email ideje za investitore, ona će sutra raditi na tome';
$labels['ai_help_example_16'] = 'profesionalnu e-poruku o ostavci, uz najavu od 1 mjeseca prema ugovoru, kompanija se zove ACME';
$labels['ai_help_example_17'] = 'uvjerljiv email za traženje promocije, nagovještavajući da bih mogao dati ostavku ako je ne dobijem jer postoje druge prilike';
$labels['ai_help_example_18'] = 'Drago mi je da smo se jučer sreli na konferenciji, uživao sam u našem razgovoru, ostanimo u kontaktu';
