<?php

$labels = [];

$labels['ai_dialog_button_title'] = 'Verfassen Sie eine Nachricht mit KI';
$labels['ai_dialog_title'] = 'Verfassen Sie eine Nachricht mit KI';
$labels['ai_options_title'] = 'AI Mail Optionen';

$labels['ai_label_to'] = 'Empfängername';
$labels['ai_label_from'] = 'Absendername';
$labels['ai_label_style'] = 'Stil';
$labels['ai_label_length'] = 'Länge';
$labels['ai_label_language'] = 'Sprache';
$labels['ai_label_creativity'] = 'Kreativität';
$labels['ai_label_instructions'] = 'Anweisungen';
$labels['ai_no_change'] = 'Keine Änderung';
$labels['ai_instructions_placeholder'] = 'Beispiel: Terminänderung für nächste Woche anfordern';

$labels['ai_style_assertive'] = 'Selbstbewusst';
$labels['ai_style_casual'] = 'Lässig';
$labels['ai_style_enthusiastic'] = 'Enthusiastisch';
$labels['ai_style_funny'] = 'Witzig';
$labels['ai_style_informational'] = 'Informativ';
$labels['ai_style_professional'] = 'Professionell';
$labels['ai_style_urgent'] = 'Dringend';
$labels['ai_style_witty'] = 'Geistreich';
$labels['ai_style_persuasive'] = 'Überzeugend';

$labels['ai_length_short'] = 'Kurz';
$labels['ai_length_medium'] = 'Mittel';
$labels['ai_length_long'] = 'Lang';

$labels['ai_creativity_low'] = 'Niedrig';
$labels['ai_creativity_medium'] = 'Mittel';
$labels['ai_creativity_high'] = 'Hoch';

$labels['ai_language_bosnian'] = 'Bosnian (Bosanski)';
$labels['ai_language_croatian'] = 'Croatian (Hrvatski)';
$labels['ai_language_english'] = 'English (US)';
$labels['ai_language_german'] = 'German (Deutsch)';
$labels['ai_language_dutch'] = 'Dutch (Nederlands)';

$labels['ai_error_sender_name'] = 'Bitte geben Sie den Absendernamen ein!';
$labels['ai_error_recipient_name'] = 'Empfängername leer (Optional)';
$labels['ai_error_instructions'] = 'Geben Sie Anweisungen ein!';
$labels['ai_general_settings'] = 'Allgemeine Einstellungen';

$labels['ai_predefined_submit'] = 'Speichern';
$labels['ai_predefined_create'] = 'Erstellen';
$labels['ai_predefined_delete'] = 'Löschen';
$labels['ai_predefined_error'] = 'Fehler';
$labels['ai_predefined_successful_save'] = 'Erfolgreich gespeichert';
$labels['ai_predefined_get_instructions_error'] = 'Fehler beim Abrufen von Anweisungen';
$labels['ai_predefined_unsuccessful_save'] = 'Fehler beim Speichern der Anweisung';
$labels['ai_predefined_successful_delete'] = 'Erfolgreich gelöscht';
$labels['ai_predefined_unsuccessful_delete'] = 'Fehler beim Löschen der Anweisung';
$labels['ai_predefined_invalid_input'] = 'Unvollständige Eingabe, eines oder mehrere Felder sind leer!';
$labels['ai_predefined_cancel'] = 'Abbrechen';
$labels['ai_predefined_popup_title'] = 'Sind Sie sicher?';
$labels['ai_predefined_popup_body'] = 'Möchten Sie diese vordefinierte Anweisung wirklich löschen?';
$labels['ai_predefined_listing_empty'] = "Die Liste ist leer. Verwenden Sie die Schaltfläche 'Erstellen', um eine neue Anweisung hinzuzufügen.";
$labels['ai_request_error'] = 'Dienst nicht verfügbar. Bitte versuchen Sie es später noch einmal.';
$labels['ai_predefined_title'] = 'Titel';
$labels['ai_predefined_content'] = 'Inhalt';
$labels['ai_predefined_section_title'] = 'AI Vorgegebene Anweisungen';
$labels['ai_predefined_modal_description'] = 'Definieren Sie Ihre eigenen vordefinierten Anweisungen im Einstellungsfeld, um die E-Mail-Generierung zu optimieren. Passen Sie diese Anweisungen an häufige Szenarien wie Namen, Daten und spezifische Details an, die Sie häufig verwenden. Sobald sie erstellt sind, können Sie sie einfach auswählen, anpassen und in die AI-Seite einfügen. Diese personalisierten Vorlagen sparen Ihnen Zeit und sorgen für Konsistenz in Ihren E-Mails.';
$labels['ai_predefined_no_instructions'] = 'Derzeit stehen Ihnen keine vordefinierten Anweisungen zur Verfügung. Erstellen Sie eine neue vordefinierte Anweisung in den Einstellungen.';
$labels['ai_predefined_edit_instructions'] = 'Bearbeite Anweisungen';
$labels['ai_predefined_use_instructions'] = 'Verwenden Sie Anweisungen';
$labels['ai_predefined_manage_instructions'] = 'Verwalten Sie Anweisungen';
$labels['ai_predefined_use_predefined_instructions'] = 'Verwende vordefinierte Anweisungen';

$labels['ai_insert_email'] = 'E-Mail einfügen';
$labels['ai_generate_email'] = 'E-Mail generieren';
$labels['ai_generate_again'] = 'Erneut generieren';
$labels['ai_stop_generating'] = 'Generierung stoppen';
$labels['ai_error_help_button'] = 'Hilfe';

$labels['ai_compose_settings'] = 'AICompose Einstellungen';
$labels['ai_compose_hide_show'] = 'Aus-/Einblenden des AICompose-Plugins';
$labels['ai_compose_hide'] = 'Verbergen';
$labels['ai_compose_show'] = 'Anzeigen';

$labels['ai_button_show_instructions'] = 'Beispielanweisungen';
$labels['ai_help_button_back'] = 'Zurück';
$labels['ai_button_fix_selected_text'] = ' Ausgewählten Text Korrigieren';
$labels['ai_help_title'] = 'Hilfe & Beispiele';
$labels['ai_help_use_example'] = '(Verwenden Sie dies)';

$labels['ai_fix_selected_text_title'] = 'Ausgewählten Text korrigieren';
$labels['ai_selected_text'] = 'Ausgewählter Text';
$labels['ai_fix_instructions'] = 'Korrekturanleitung';

$labels['ai_generate_again'] = 'Erneut generieren';
$labels['ai_fix_text_input_instructions'] = 'Geben Sie in dieses Feld detaillierte Erklärungen oder Anweisungen zu den Änderungen ein, die Sie am ausgewählten Text vornehmen möchten.';

$labels['settings_menu_text'] = 'Künstliche Intelligenz';
$labels['setting_default_options'] = 'Verfassen von Nachrichten mit KI';
$labels['setting_ai_style'] = 'Stil';
$labels['setting_ai_length'] = 'Länge';
$labels['setting_ai_language'] = 'Sprache';
$labels['setting_ai_creativity'] = 'Kreativität';

$labels['ai_tip_to'] = 'Name des Empfängers der neuen E-Mail. Sie können mehrere Namen angeben oder Begriffe wie "alle", "Team" usw. verwenden.';
$labels['ai_tip_from'] = 'Die neue E-Mail wird mit diesem Namen unterzeichnet.';
$labels['ai_tip_style'] = 'Der gewünschte Schreibstil für die neue E-Mail.';
$labels['ai_tip_length'] = 'Die gewünschte Länge der neuen E-Mail.';
$labels['ai_tip_language'] = 'Die Sprache, in der die neue E-Mail geschrieben werden soll. Geben Sie "Keine Änderung" an, um in der Sprache zu schreiben, in der die Anweisungen gegeben wurden.';
$labels['ai_tip_creativity'] = 'Höhere Kreativität erzeugt unvorhersehbarere und abwechslungsreichere E-Mails; niedrigere Kreativität erzeugt faktischere und präzisere E-Mails.';
$labels['ai_tip_instructions'] = 'Anweisungen, was in die neue E-Mail aufgenommen werden soll. Klicken Sie auf die Schaltfläche "Beispielanweisungen", um einige Beispiele zu sehen.';

$labels['ai_help_info'] = 'Erzählen Sie der KI von der E-Mail, die Sie schreiben möchten. Geben Sie Details wie Namen, Daten, Orte, Gründe usw. an. Sie können auch nach kreativen Ideen oder Erklärungen fragen. Sobald die E-Mail generiert ist, können Sie sie anpassen und in die KI-Seite einfügen. Hier sind einige Beispielanweisungen zum Starten';

$labels['ai_help_example_1'] = 'grüße dich';
$labels['ai_help_example_2'] = 'das heutige Meeting wurde abgesagt';
$labels['ai_help_example_3'] = 'Ich habe ein Meeting mit Margy am Mittwoch um 15:00 Uhr vereinbart. Ich habe eine Präsentation über die Vorteile der Nutzung von Künstlicher Intelligenz in unseren Marketingkampagnen vorbereitet, um sie zu überzeugen.';
$labels['ai_help_example_4'] = 'Wir haben uns entschieden, Unterstützung für KI-generierte Inhalte hinzuzufügen. Erkläre kurz, was das ist.';
$labels['ai_help_example_5'] = 'Fortsetzung der Aufgabe von letzter Woche, ich brauche sie morgen.';
$labels['ai_help_example_6'] = 'Fordere eine Gehaltserhöhung an, ich habe seit über einem Jahr keine bekommen.';
$labels['ai_help_example_7'] = 'Erinnere daran, dass der Bericht morgen eingereicht werden muss, sonst wird das Team Probleme mit Margy haben, die gestresst ist.';
$labels['ai_help_example_8'] = 'Schreibe den Kunden über 20% Rabatt auf alle Produkte bis Dienstag, wir verkaufen Kleidung.';
$labels['ai_help_example_9'] = 'Bitte schreibe Laura und sage ihr, dass sie eine Party für Kevins Geburtstag dieses Wochenende organisieren soll.';
$labels['ai_help_example_10'] = 'Frage nach dem Fortschritt mit der neuen Website und füge 5 Ideen für Marketing-Slogans für die Startseite hinzu. Wir reparieren Autos.';
$labels['ai_help_example_11'] = 'Informationsblatt über neue VPN-Funktionen, die wir hinzugefügt haben: WireGuard-Protokoll, Portweiterleitung, Kill Switch, dedizierte IP; erkläre, was das ist.';
$labels['ai_help_example_12'] = 'Informationsblatt über das neue Treueprogramm. Die Anfangskosten betragen 10$ für eine Karte, danach gibt es bis zu 20% Rabatt auf die meisten Produkte für ein Jahr.';
$labels['ai_help_example_13'] = 'Netzwerken per E-Mail mit jemandem, den ich bewundere und mit dem ich mich beruflich vernetzen möchte.';
$labels['ai_help_example_14'] = 'Professionelle Danksagung für die Hilfe bei einem Projekt gestern.';
$labels['ai_help_example_15'] = 'Überlege dir 10 Ideen für Strategien, um eine effektive E-Mail für Investoren zu erstellen. Sie wird morgen daran arbeiten.';
$labels['ai_help_example_16'] = 'Professionelle Rücktritts-E-Mail mit einer Ankündigung von 1 Monat gemäß Vertrag. Die Firma heißt ACME.';
$labels['ai_help_example_17'] = 'Überzeugende E-Mail zur Anfrage einer Beförderung, mit dem Hinweis, dass ich möglicherweise kündigen könnte, wenn ich sie nicht erhalte, da es andere Möglichkeiten gibt.';
$labels['ai_help_example_18'] = 'Ich freue mich, dass wir uns gestern auf der Konferenz getroffen haben. Ich habe unser Gespräch genossen, lass uns in Kontakt bleiben.';
