<?php

$labels = [];

$labels['ai_dialog_button_text'] = 'AI';
$labels['ai_dialog_button_title'] = 'Compose message using AI';
$labels['ai_dialog_title'] = 'Compose message using AI';

$labels['ai_label_to'] = 'Recipient name';
$labels['ai_label_from'] = 'Sender name';
$labels['ai_label_style'] = 'Style';
$labels['ai_label_length'] = 'Length';
$labels['ai_label_language'] = 'Language';
$labels['ai_label_creativity'] = 'Creativity';
$labels['ai_label_instructions'] = 'Instructions';
$labels['ai_no_change'] = 'No change';
$labels['ai_instructions_placeholder'] = 'Example: request a change of appointment for next week';

$labels['ai_style_assertive'] = 'Assertive';
$labels['ai_style_casual'] = 'Casual';
$labels['ai_style_enthusiastic'] = 'Enthusiastic';
$labels['ai_style_funny'] = 'Funny';
$labels['ai_style_informational'] = 'Informational';
$labels['ai_style_professional'] = 'Professional';
$labels['ai_style_urgent'] = 'Urgent';
$labels['ai_style_witty'] = 'Witty';
$labels['ai_style_persuasive'] = 'Persuasive';

$labels['ai_length_short'] = 'Short';
$labels['ai_length_medium'] = 'Medium';
$labels['ai_length_long'] = 'Long';

$labels['ai_creativity_low'] = 'Low';
$labels['ai_creativity_medium'] = 'Medium';
$labels['ai_creativity_high'] = 'High';

$labels['ai_language_bosnian'] = 'Bosnian (Bosanski)';
$labels['ai_language_croatian'] = 'Croatian (Hrvatski)';
$labels['ai_language_english'] = 'English (US)';
$labels['ai_language_german'] = 'German (Deutsch)';
$labels['ai_language_dutch'] = 'Dutch (Nederlands)';

$labels['ai_error_sender_name'] = "Enter the sender's name!";
$labels['ai_error_recipient_name'] = "Recipient's name is empty (Optional)";
$labels['ai_error_instructions'] = 'Enter instructions!';

$labels['ai_request_error'] = 'Service unavailable. Please try again later.';

$labels['ai_insert_email'] = 'Insert email';
$labels['ai_generate_email'] = 'Generate email';
$labels['ai_generate_again'] = 'Generate again';
$labels['ai_stop_generating'] = 'Stop generating';
$labels['ai_error_help_button'] = 'Help';

$labels['ai_button_show_instructions'] = 'Instruction Examples';
$labels['ai_help_button_back'] = 'Back';
$labels['ai_button_fix_selected_text'] = 'Fix Selected Text';
$labels['ai_help_title'] = 'Help & Examples';
$labels['ai_help_use_example'] = '(Use this)';

$labels['ai_compose_settings'] = 'AICompose Settings';

$labels['ai_predefined_submit'] = 'Save';
$labels['ai_predefined_create'] = 'Create';
$labels['ai_predefined_delete'] = 'Delete';
$labels['ai_predefined_successful_save'] = 'Successfully saved';
$labels['ai_predefined_unsuccessful_save'] = 'Error saving the message';
$labels['ai_predefined_successful_delete'] = 'Successfully deleted';
$labels['ai_predefined_unsuccessful_delete'] = 'Error deleting the message';
$labels['ai_predefined_invalid_input'] = 'Invalid input';
$labels['ai_predefined_cancel'] = 'Cancel';
$labels['ai_predefined_popup_title'] = 'Are you sure?';
$labels['ai_predefined_popup_body'] = 'Do you really want to delete this predefined instruction?';
$labels['ai_predefined_listing_empty'] = 'The list is empty. Use the Create button to add a new instruction.';
$labels['ai_predefined_title'] = 'Title';
$labels['ai_predefined_content'] = 'Content';
$labels['ai_predefined_section_title'] = 'AI Predefined Instructions';

$labels['ai_fix_selected_text_title'] = 'Fix Selected Text';
$labels['ai_selected_text'] = 'Selected Text';
$labels['ai_fix_instructions'] = 'Correction Instructions';

$labels['ai_generate_again'] = 'Generate Again';
$labels['ai_fix_text_input_instructions'] = 'In this field, enter detailed explanations or instructions about the changes you want to make to the selected text.';

$labels['settings_menu_text'] = 'Artificial Intelligence';
$labels['setting_default_options'] = 'Compose messages with AI';
$labels['setting_ai_style'] = 'Style';
$labels['setting_ai_length'] = 'Length';
$labels['setting_ai_language'] = 'Language';
$labels['setting_ai_creativity'] = 'Creativity';

$labels['ai_tip_to'] = 'Recipient name for the new email. You can specify more than one name or use phrases like "everyone", "team", etc.';
$labels['ai_tip_from'] = 'The new email will be signed with this name.';
$labels['ai_tip_style'] = 'The desired writing style for the new email.';
$labels['ai_tip_length'] = 'The desired length of the new email.';
$labels['ai_tip_language'] = 'The language in which the new email should be written. Specify "No change" to write in the language in which the instructions are given.';
$labels['ai_tip_creativity'] = 'Higher creativity will generate more unpredictable and diverse emails; lower creativity will generate emails that are more factual and precise.';
$labels['ai_tip_instructions'] = 'Instructions on what to include in the new email. Click the Instruction Examples button to see some examples.';

$labels['ai_help_info'] = 'Tell the AI about the email you want to write. Include details such as names, dates, locations, reasons, etc. You can also ask for creative ideas or explanations. Once the email is generated, you will be able to adjust it and insert it into the AI page. Here are some example instructions to get started:';

$labels['ai_help_example_1'] = 'say hello';
$labels['ai_help_example_2'] = 'today’s meeting is canceled';
$labels['ai_help_example_3'] = 'I have scheduled a meeting with Margy on Wednesday at 3:00 PM, and I have prepared a presentation on the benefits of using artificial intelligence in our marketing campaigns to convince her';
$labels['ai_help_example_4'] = 'we decided to add support for AI-generated content, briefly explain what it is';
$labels['ai_help_example_5'] = 'follow-up on the task from last week, I need it tomorrow';
$labels['ai_help_example_6'] = 'ask for a raise, I haven’t gotten one in over a year';
$labels['ai_help_example_7'] = 'remind them to submit the report tomorrow or the team will have problems with Margy, who is stressed';
$labels['ai_help_example_8'] = 'write to customers about a 20% discount on all products until Tuesday, we sell clothes';
$labels['ai_help_example_9'] = 'ask to write to Laura and tell her to organize a gathering for Kevin’s birthday this weekend';
$labels['ai_help_example_10'] = 'ask about progress with the new website, include 5 ideas for marketing slogans for the homepage, we do car repairs';
$labels['ai_help_example_11'] = 'information sheet about the new VPN features we’ve added: wireguard protocol, port forwarding, kill switch, dedicated IP; explain what they are';
$labels['ai_help_example_12'] = 'information sheet about the new loyalty program, initial cost is $10 for the card, then up to 20% discount on most products for a year';
$labels['ai_help_example_13'] = 'networking email to someone I admire and want to connect with professionally';
$labels['ai_help_example_14'] = 'professionally expressing gratitude for yesterday’s help with the project';
$labels['ai_help_example_15'] = 'come up with 10 ideas on strategies for creating an effective email idea for investors, she’ll be working on it tomorrow';
$labels['ai_help_example_16'] = 'professional resignation email with a 1-month notice per contract, the company is called ACME';
$labels['ai_help_example_17'] = 'persuasive email to ask for a promotion, hinting that I might resign if I don’t get it because there are other opportunities';
$labels['ai_help_example_18'] = 'I’m glad we met at the conference yesterday, I enjoyed our conversation, let’s stay in touch';
