<?php

$labels = [];

$labels['ai_dialog_button_title'] = 'Sastavite poruku pomoću AI';
$labels['ai_dialog_title'] = 'Sastavite poruku pomoću AI';

$labels['ai_label_to'] = 'Ime primatelja';
$labels['ai_label_from'] = 'Ime pošiljatelja';
$labels['ai_label_style'] = 'Stil';
$labels['ai_label_length'] = 'Dužina';
$labels['ai_label_language'] = 'Jezik';
$labels['ai_label_creativity'] = 'Kreativnost';
$labels['ai_label_instructions'] = 'Upute';
$labels['ai_no_change'] = 'Bez promjene';
$labels['ai_instructions_placeholder'] = 'Primjer: zatražite promjenu termina za sljedeći tjedan';

$labels['ai_style_assertive'] = 'Samouvjereno';
$labels['ai_style_casual'] = 'Neformalno';
$labels['ai_style_enthusiastic'] = 'Entuzijastično';
$labels['ai_style_funny'] = 'Smiješno';
$labels['ai_style_informational'] = 'Informativno';
$labels['ai_style_professional'] = 'Profesionalno';
$labels['ai_style_urgent'] = 'Hitno';
$labels['ai_style_witty'] = 'Domisleno';
$labels['ai_style_persuasive'] = 'Uvjerljivo';

$labels['ai_length_short'] = 'Kratko';
$labels['ai_length_medium'] = 'Srednje';
$labels['ai_length_long'] = 'Dugo';

$labels['ai_creativity_low'] = 'Nisko';
$labels['ai_creativity_medium'] = 'Srednje';
$labels['ai_creativity_high'] = 'Visoko';

$labels['ai_language_bosnian'] = 'Bosnian (Bosanski)';
$labels['ai_language_croatian'] = 'Croatian (Hrvatski)';
$labels['ai_language_english'] = 'English (US)';
$labels['ai_language_german'] = 'German (Deutsch)';
$labels['ai_language_dutch'] = 'Dutch (Nederlands)';

$labels['ai_error_sender_name'] = 'Unesite ime pošiljatelja!';
$labels['ai_error_recipient_name'] = ' Ime primatelja prazno (Opcionalno)';
$labels['ai_error_instructions'] = 'Unesite upute!';

$labels['ai_request_error'] = 'Usluga nije dostupna. Molimo pokušajte ponovo kasnije.
';

$labels['ai_insert_email'] = 'Umetni e-mail';
$labels['ai_generate_email'] = 'Generiraj e-mail';
$labels['ai_generate_again'] = 'Generiraj ponovo';
$labels['ai_stop_generating'] = 'Zaustavi Generiranje';
$labels['ai_error_help_button'] = 'Pomoć';

$labels['ai_predefined_submit'] = 'Spremi';
$labels['ai_predefined_create'] = 'Kreiraj';
$labels['ai_predefined_delete'] = 'Izbriši';
$labels['ai_predefined_error'] = 'Greška';
$labels['ai_predefined_successful_save'] = 'Uspješno spremljeno';
$labels['ai_predefined_get_instructions_error'] = 'Greška prilikom dohvaćanja instrukcija';
$labels['ai_predefined_unsuccessful_save'] = 'Greška prilikom spremanja upute';
$labels['ai_predefined_successful_delete'] = 'Uspješno izbrisano';
$labels['ai_predefined_unsuccessful_delete'] = 'Greška prilikom brisanja upute';
$labels['ai_predefined_invalid_input'] = 'Nepotpun unos, jedno ili više polja je prazno!';
$labels['ai_predefined_cancel'] = 'Otkaži';
$labels['ai_predefined_popup_title'] = 'Jeste li sigurni?';
$labels['ai_predefined_popup_body'] = 'Želite li zaista obrisati ovu predefiniranu instrukciju?';
$labels['ai_predefined_listing_empty'] = "Lista je prazna. Iskoristite gumb 'Kreiraj' za dodavanje nove instrukcije.";
$labels['ai_predefined_title'] = 'Naslov';
$labels['ai_predefined_content'] = 'Sadržaj';
$labels['ai_predefined_section_title'] = 'AI Predefinirane Upute';
$labels['ai_predefined_modal_description'] = 'Definirajte vlastite unaprijed definirane upute u polju postavki kako biste olakšali generiranje e-pošte. Prilagodite ove upute uobičajenim scenarijima kao što su imena, datumi i specifični detalji koje često koristite. Kada ih kreirate, lako ih možete odabrati, prilagoditi i umetnuti na AI stranicu. Ovi personalizirani obrasci će vam uštedjeti vrijeme i osigurati dosljednost u vašim e-porukama.';
$labels['ai_predefined_no_instructions'] = 'Trenutno nemate dostupnih unaprijed definiranih uputa. Napravite novu unaprijed definiranu uputu u postavkama.';
$labels['ai_predefined_edit_instructions'] = 'Uredi instrukcije';
$labels['ai_predefined_use_instructions'] = 'Koristi instrukcije';
$labels['ai_predefined_manage_instructions'] = 'Upravljaj instrukcijama';
$labels['ai_predefined_use_predefined_instructions'] = 'Koristi unaprijed definirane instrukcije';

$labels['ai_button_show_instructions'] = 'Primjeri Uputa';
$labels['ai_help_button_back'] = 'Natrag';
$labels['ai_button_fix_selected_text'] = 'Ispravi Odabrani Tekst';
$labels['ai_help_title'] = 'Pomoć & Primjeri';
$labels['ai_help_use_example'] = '(Koristi ovo)';

$labels['ai_compose_settings'] = 'AICompose Postavke';

$labels['ai_fix_selected_text_title'] = 'Ispravi Odabrani Tekst';
$labels['ai_selected_text'] = 'Odabrani Tekst';
$labels['ai_fix_instructions'] = 'Upute za Ispravljanje';

$labels['ai_generate_again'] = 'Generiraj ponovo';
$labels['ai_fix_text_input_instructions'] = 'U ovom polju unesite detaljna objašnjenja ili upute o izmjenama koje želite napraviti na odabranom tekstu.';

$labels['settings_menu_text'] = 'Umjetna Inteligencija';
$labels['setting_default_options'] = 'Sastavljanje poruka s AI';
$labels['setting_ai_style'] = 'Stil';
$labels['setting_ai_length'] = 'Dužina';
$labels['setting_ai_language'] = 'Jezik';
$labels['setting_ai_creativity'] = 'Kreativnost';

$labels['ai_tip_to'] = 'Ime primatelja nove e-pošte. Možete navesti više od jednog imena ili koristiti izraze poput "svi", "tim" itd.';
$labels['ai_tip_from'] = 'Novi email će biti potpisan ovim imenom.';
$labels['ai_tip_style'] = 'Željeni stil pisanja za novu e-poštu.';
$labels['ai_tip_length'] = 'Željena dužina nove e-pošte.';
$labels['ai_tip_language'] = 'Jezik na kojem bi trebao biti napisan novi email. Navedite "Bez promjene" da pišete na jeziku na kojem su dane upute.';
$labels['ai_tip_creativity'] = 'Veća kreativnost će generirati nepredvidivije i raznolikije e-poruke; niža kreativnost će generirati e-poruke koje su više činjenične i točnije.';
$labels['ai_tip_instructions'] = 'Upute o tome što uključiti u novu e-poštu. Kliknite na gumb Primjeri Uputa kako biste vidjeli neke primjere.';

$labels['ai_help_info'] = 'Recite AI o e-poruci koju želite napisati. Uključite pojedinosti kao što su imena, datumi, lokacije, razlozi itd. Također možete tražiti kreativne ideje ili objašnjenja. Nakon što se e-mail generira, moći ćete ga prilagoditi i umetnuti u AI stranicu. Evo nekoliko primjera uputa za početak';

$labels['ai_help_example_1'] = 'pozdravi se';
$labels['ai_help_example_2'] = 'današnji sastanak je otkazan';
$labels['ai_help_example_3'] = 'Dogovorio sam sastanak s Margy u srijedu u 15:00, pripremio sam prezentaciju o prednostima korištenja umjetne inteligencije u našim marketinškim kampanjama da je uvjerim';
$labels['ai_help_example_4'] = 'odlučili smo dodati podršku za sadržaj generiran umjetnom inteligencijom, objasni ukratko što je to';
$labels['ai_help_example_5'] = 'nastavak radnog zadatka od prošlog tjedna, trebam ga sutra';
$labels['ai_help_example_6'] = 'traži povišicu, nisam je dobio više od godinu dana';
$labels['ai_help_example_7'] = 'podsjetite da se sutra preda izvještaj ili će tim imati problema s Margy koja je pod stresom';
$labels['ai_help_example_8'] = 'pišite kupcima o 20% popusta na sve proizvode do utorka, prodajemo odjeću';
$labels['ai_help_example_9'] = 'zamolite da napišete Lauri i recite joj da organizira druženje za Kevinov rođendan ovog vikenda';
$labels['ai_help_example_10'] = 'pitajte o napretku s novom web-stranicom, uključite 5 ideja za marketinške slogane za naslovnu stranicu, bavimo se popravcima automobila';
$labels['ai_help_example_11'] = 'informativni list o novim VPN funkcijama koje smo dodali: wireguard protokol, prosljeđivanje portova, kill switch, namjenski IP; objasni što su';
$labels['ai_help_example_12'] = 'informativni list o novom programu lojalnosti, početni trošak je 10$ za karticu, a zatim do 20% popusta na većinu proizvoda za godinu dana';
$labels['ai_help_example_13'] = 'umrežavanje e-poštom s nekim kome se divim i s kim se želim profesionalno povezati';
$labels['ai_help_example_14'] = 'profesionalno izražavanje zahvalnosti za jučerašnju pomoć oko projekta';
$labels['ai_help_example_15'] = 'smisli 10 ideja o strategijama za kreiranje učinkovite email ideje za investitore, ona će sutra raditi na tome';
$labels['ai_help_example_16'] = 'profesionalni email o ostavci, uz najavu od 1 mjeseca prema ugovoru, tvrtka se zove ACME';
$labels['ai_help_example_17'] = 'uvjerljiv email za traženje promaknuća, nagovještavajući da bih mogao dati otkaz ako ga ne dobijem jer postoje druge prilike';
$labels['ai_help_example_18'] = 'Drago mi je da smo se jučer sreli na konferenciji, uživao sam u našem razgovoru, ostanimo u kontaktu';
