<?php

$labels = [];

$labels['ai_dialog_button_title'] = 'Stel een bericht samen met AI';
$labels['ai_dialog_title'] = 'Stel een bericht samen met AI';

$labels['ai_label_to'] = 'Naam ontvanger';
$labels['ai_label_from'] = 'Naam afzender';
$labels['ai_label_style'] = 'Stijl';
$labels['ai_label_length'] = 'Lengte';
$labels['ai_label_language'] = 'Taal';
$labels['ai_label_creativity'] = 'Creativiteit';
$labels['ai_label_instructions'] = 'Instructies';
$labels['ai_no_change'] = 'Geen wijziging';
$labels['ai_instructions_placeholder'] = 'Bijvoorbeeld: vraag om een afspraak te verzetten voor volgende week';

$labels['ai_style_assertive'] = 'Zelfverzekerd';
$labels['ai_style_casual'] = 'Informeel';
$labels['ai_style_enthusiastic'] = 'Enthousiast';
$labels['ai_style_funny'] = 'Grappig';
$labels['ai_style_informational'] = 'Informatief';
$labels['ai_style_professional'] = 'Professioneel';
$labels['ai_style_urgent'] = 'Urgent';
$labels['ai_style_witty'] = 'Geestig';
$labels['ai_style_persuasive'] = 'Overtuigend';

$labels['ai_length_short'] = 'Kort';
$labels['ai_length_medium'] = 'Middel';
$labels['ai_length_long'] = 'Lang';

$labels['ai_creativity_low'] = 'Laag';
$labels['ai_creativity_medium'] = 'Middel';
$labels['ai_creativity_high'] = 'Hoog';

$labels['ai_language_bosnian'] = 'Bosnian (Bosanski)';
$labels['ai_language_croatian'] = 'Croatian (Hrvatski)';
$labels['ai_language_english'] = 'English (US)';
$labels['ai_language_german'] = 'German (Deutsch)';
$labels['ai_language_dutch'] = 'Dutch (Nederlands)';

$labels['ai_error_sender_name'] = 'Voer de afzendernaam in!';
$labels['ai_error_recipient_name'] = 'Ontvangernaam is leeg (Optioneel)';
$labels['ai_error_instructions'] = 'Voer instructies in!';

$labels['ai_request_error'] = 'Dienst niet beschikbaar. Probeer het later nog eens.';

$labels['ai_insert_email'] = 'E-mail invoegen';
$labels['ai_generate_email'] = 'E-mail genereren';
$labels['ai_generate_again'] = 'Opnieuw genereren';
$labels['ai_stop_generating'] = 'Stop met genereren';
$labels['ai_error_help_button'] = 'Help';

$labels['ai_general_settings'] = "Algemene instellingen";

$labels['ai_predefined_submit'] = 'Opslaan';
$labels['ai_predefined_create'] = 'Aanmaken';
$labels['ai_predefined_delete'] = 'Verwijderen';
$labels['ai_predefined_error'] = 'Fout';
$labels['ai_predefined_get_instructions_error'] = 'Fout bij het ophalen van instructies';
$labels['ai_predefined_successful_save'] = 'Succesvol opgeslagen';
$labels['ai_predefined_unsuccessful_save'] = 'Fout bij het opslaan van de instructie';
$labels['ai_predefined_successful_delete'] = 'Succesvol verwijderd';
$labels['ai_predefined_unsuccessful_delete'] = 'Fout bij het verwijderen van de instructie';
$labels['ai_predefined_cancel'] = 'Annuleren';
$labels['ai_predefined_popup_title'] = 'Weet je het zeker?';
$labels['ai_predefined_invalid_input'] = 'Onvolledige invoer, een of meer velden zijn leeg!';
$labels['ai_predefined_popup_body'] = 'Wilt u deze vooraf gedefinieerde instructie echt verwijderen?';
$labels['ai_predefined_listing_empty'] = "De lijst is leeg. Gebruik de knop 'Aanmaken' om een nieuwe instructie toe te voegen.";
$labels['ai_predefined_title'] = 'Titel';
$labels['ai_predefined_content'] = 'Inhoud';
$labels['ai_predefined_section_title'] = 'AI Vooraf gedefinieerde instructies';
$labels['ai_predefined_modal_description'] = "Definieer uw eigen vooraf gedefinieerde instructies in het instellingenveld om het genereren van e-mails te stroomlijnen. Pas deze instructies aan op veelvoorkomende scenario's zoals namen, data en specifieke details die u vaak gebruikt. Zodra ze zijn aangemaakt, kunt u ze eenvoudig selecteren, aanpassen en in de AI-pagina invoegen. Deze gepersonaliseerde sjablonen besparen u tijd en zorgen voor consistentie in uw e-mails.";
$labels['ai_predefined_no_instructions'] = 'Trenutno nemate dostupnih unaprijed definiranih uputa. Napravite novu unaprijed definiranu uputu u postavkama.';
$labels['ai_predefined_edit_instructions'] = 'Bewerk instructies';
$labels['ai_predefined_use_instructions'] = 'Gebruik instructies';
$labels['ai_predefined_manage_instructions'] = 'Beheer instructies';
$labels['ai_predefined_use_predefined_instructions'] = 'Gebruik vooraf gedefinieerde instructies';

$labels['ai_button_show_instructions'] = 'Voorbeelden van instructies';
$labels['ai_help_button_back'] = 'Terug';
$labels['ai_button_fix_selected_text'] = 'Geselecteerde Tekst Corrigeren';
$labels['ai_help_title'] = 'Help & Voorbeelden';
$labels['ai_help_use_example'] = '(Gebruik dit)';

$labels['ai_fix_selected_text_title'] = 'Geselecteerde Tekst Corrigeren';
$labels['ai_selected_text'] = 'Geselecteerde Tekst';
$labels['ai_fix_instructions'] = 'Instructies voor Correctie';

$labels['ai_compose_settings'] = 'AICompose Instellingen';

$labels['ai_generate_again'] = 'Genereer opnieuw';
$labels['ai_fix_text_input_instructions'] = 'Voer in dit veld gedetailleerde uitleg of instructies in over de wijzigingen die u wilt aanbrengen in de geselecteerde tekst.';

$labels['settings_menu_text'] = 'Kunstmatige Intelligentie';
$labels['setting_default_options'] = 'Berichten samenstellen met AI';
$labels['setting_ai_style'] = 'Stijl';
$labels['setting_ai_length'] = 'Lengte';
$labels['setting_ai_language'] = 'Taal';
$labels['setting_ai_creativity'] = 'Creativiteit';

$labels['ai_tip_to'] = 'Naam van de ontvanger van de nieuwe e-mail. U kunt meer dan één naam opgeven of groepen gebruiken zoals "allen", "team", enzovoort.';
$labels['ai_tip_from'] = 'De nieuwe e-mail zal onderteken worden met deze naam.';
$labels['ai_tip_style'] = 'Gewenste schrijfstijl voor de nieuwe e-mail.';
$labels['ai_tip_length'] = 'Gewenste lengte van de nieuwe e-mail.';
$labels['ai_tip_language'] = 'De taal waarin de nieuwe e-mail moet worden geschreven. Geef "Geen wijziging" op als u in de taal wilt schrijven waarin de instructies zijn gegeven.';
$labels['ai_tip_creativity'] = 'Hogere creativiteit zal onvoorspelbaardere en gevarieerdere e-mails genereren; lagere creativiteit zal e-mails genereren die feitelijker en preciezer zijn.';
$labels['ai_tip_instructions'] = 'Instructies over wat in de nieuwe e-mail moet worden opgenomen. Klik op de knop Voorbeelden van Instructies om enkele voorbeelden te bekijken.';

$labels['ai_help_info'] = 'Vertel AI over de e-mail die je wilt schrijven. Vermeld details zoals namen, data, locaties, redenen, enzovoort. U kunt ook vragen om creatieve ideeën of uitleg. Nadat de e-mail is gegenereerd, kunt u deze aanpassen en invoegen op de AI-pagina. Hier zijn enkele voorbeelden van instructies om te beginnen';

$labels['ai_help_example_1'] = 'groet';
$labels['ai_help_example_2'] = 'de vergadering van vandaag is geannuleerd';
$labels['ai_help_example_3'] = 'Ik heb een vergadering met Margy op woensdag om 15:00 uur gepland, ik heb een presentatie voorbereid over de voordelen van het gebruik van kunstmatige intelligentie in onze marketingcampagnes om haar te overtuigen';
$labels['ai_help_example_4'] = 'we hebben besloten om ondersteuning toe te voegen voor door AI gegenereerde inhoud, leg kort uit wat dat is';
$labels['ai_help_example_5'] = 'voortgang van de taak van vorige week, ik heb het morgen nodig';
$labels['ai_help_example_6'] = 'vraag om een loonsverhoging, ik heb er al meer dan een jaar geen gekregen';
$labels['ai_help_example_7'] = 'herinner aan het inleveren van het rapport morgen of het team zal problemen hebben met Margy die onder stress staat';
$labels['ai_help_example_8'] = 'schrijf naar klanten over 20% korting op alle producten tot dinsdag, we verkopen kleding';
$labels['ai_help_example_9'] = 'vraag om Lauri te schrijven en haar te vragen een bijeenkomst te organiseren voor Kevins verjaardag dit weekend';
$labels['ai_help_example_10'] = 'vraag naar de voortgang van de nieuwe website, voeg 5 ideeën toe voor marketing slogans voor de startpagina, we doen autoreparaties';
$labels['ai_help_example_11'] = 'informatief blad over de nieuwe VPN-functies die we hebben toegevoegd: wireguard protocol, poort forwarding, kill switch, dedicated IP; leg uit wat ze zijn';
$labels['ai_help_example_12'] = 'informatief blad over het nieuwe loyaliteitsprogramma, initiële kosten zijn 10$ voor de kaart, daarna tot 20% korting op de meeste producten voor een jaar';
$labels['ai_help_example_13'] = 'netwerken via e-mail met iemand die ik bewonder en met wie ik professioneel wil verbinden';
$labels['ai_help_example_14'] = 'professionele dankbetuiging voor de hulp bij het project gisteren';
$labels['ai_help_example_15'] = 'bedenk 10 ideeën over strategieën voor het creëren van effectieve e-mailideeën voor investeerders, zij zal hier morgen aan werken';
$labels['ai_help_example_16'] = 'professionele e-mail over ontslag, met een opzegtermijn van 1 maand volgens het contract, het bedrijf heet ACME';
$labels['ai_help_example_17'] = 'overtuigende e-mail om promotie te vragen, suggererend dat ik kan opstappen als ik het niet krijg omdat er andere kansen zijn';
$labels['ai_help_example_18'] = 'Het was fijn om je gisteren op de conferentie te ontmoeten, ik heb genoten van ons gesprek, laten we in contact blijven';
